### ISSUE TITLE
Gitsign fails to validate commits after public instance migration

### ISSUE THREAD

**Issue by wlynch** [sigstore/gitsign#49]
**Description**

There's upstream changes being made to the public sigstore instance, and it looks like it's affecting gitsign.

```sh
$ git commit --allow-empty --message="foo"
[foo e703bda] foo 

$ git verify-commit HEAD
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101ef78f4]

goroutine 1 [running]:
main.verifyDetached()
        /Users/wlynch/go/pkg/mod/github.com/sigstore/gitsign@v0.0.2-alpha/command_verify.go:109 +0x4e4
main.commandVerify()
        /Users/wlynch/go/pkg/mod/github.com/sigstore/gitsign@v0.0.2-alpha/command_verify.go:25 +0x54
main.runCommand()
        /Users/wlynch/go/pkg/mod/github.com/sigstore/gitsign@v0.0.2-alpha/main.go:102 +0x60c
main.main()
        /Users/wlynch/go/pkg/mod/github.com/sigstore/gitsign@v0.0.2-alpha/main.go:47 +0x20
```

**Version**

`v0.0.2-alpha`

**Comment by wlynch** [comment]
to be clear - this is a bug in gitsign that was uncovered by the upstream changes to fulcio, not an issue with fulcio that would require a rollback of the public instance.
